Updates Pull Request Template
NewSpring/ApollosProject pull request #130
Opened 2019-06-05 01:06 UTC by redreceipt

## DESCRIPTION

### What does this PR do, or why is it needed?

Removes a redundant line and changes to *one* relevant reviewer.

### How do I test this PR?

You don't.

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [ ] Set a relevant reviewer

## REVIEW

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

---

> The purpose of PR Review is to _improve the quality of the software._

2019-06-05 20:43 UTC, IsaacHardy requested changes
I recommend to completely remove the "Questions to consider section" and add two more check boxes for the reviewer. Something like 1. Check code 2. Check test

2019-06-05 20:44 UTC, IsaacHardy commented
What you have already changed, looks great.

2019-06-06 13:02 UTC, IsaacHardy commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Test the fix/feature
I ment to check unit tests, snapshots, etc...

2019-06-06 14:26 UTC, redreceipt commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Test the fix/feature
```suggestion
- [ ] Review updates to test coverage and snapshots
```

2019-06-06 14:27 UTC, IsaacHardy submitted a review, later dismissed
LGTM

2019-06-06 14:35 UTC, redreceipt commented on .github/PULL_REQUEST_TEMPLATE.md
> +### Was anything changed? Why?
```suggestion
```

2019-06-06 14:35 UTC, redreceipt commented on .github/PULL_REQUEST_TEMPLATE.md
> +
```suggestion
```

2019-06-06 14:46 UTC, IsaacHardy approved these changes

2019-06-06 14:46 UTC, merged