Adds "With You" Screen After Adding Prayer
NewSpring/ApollosProject pull request #173
Opened 2019-07-10 15:38 UTC by redreceipt

## DESCRIPTION

### What does this PR do, or why is it needed?

This adds a screen that let's them go straight to praying for other people or go back and add another prayer.

### How do I test this PR?

Add some prayers!

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

2019-07-10 15:49 UTC, redreceipt commented on packages/newspringchurchapp/src/prayer/AddPrayer/WithYou/index.js
> +  // TODO: this should clear out the stack instead of just
```suggestion
```

2019-07-10 15:49 UTC, redreceipt commented on packages/newspringchurchapp/src/prayer/AddPrayer/WithYou/index.js
> +  // navigating, leaving the AddPrayerForm and this screen in the stack
```suggestion
```

2019-07-10 15:49 UTC, redreceipt commented on packages/newspringchurchapp/src/prayer/AddPrayer/WithYou/index.js
> +          // TODO: this should pop off this and the AddPrayerForm first
```suggestion
```

2019-07-10 15:58 UTC, richarddubay requested changes
Currently the prayer list doesn't work ... but the screen looks great! Just get that prayer list working and I'll re-review.

2019-07-10 21:42 UTC, richarddubay commented on packages/newspringchurchapp/src/prayer/PrayerList/index.js
> +      <ModalView onClose={() => this.props.navigation.navigate('Prayer')}>
```suggestion
      <ModalView onClose={() => this.props.navigation.popToTop()}>
```

What do you think about this?

2019-07-11 14:00 UTC, richarddubay approved these changes
:shipit:

2019-07-11 15:35 UTC, merged