Updates PR Template
NewSpring/ApollosProject pull request #3
Opened 2019-03-25 18:57 UTC by IsaacHardy

## DESCRIPTION

### What does this PR do, or why is it needed?

### What design trade-offs/decisions were made?

### How do I test this PR?

### What automated tests did you write?

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

2019-03-25 19:43 UTC, richarddubay submitted a review, later dismissed

2019-03-25 19:44 UTC, cdanwards submitted a review, later dismissed

2019-03-26 13:44 UTC, redreceipt requested changes

2019-03-26 13:44 UTC, redreceipt commented on .github/PULL_REQUEST_TEMPLATE.md
> +### Is this your best work? (Ecclesiastes 9:10 - MSG)
```suggestion
### Is this your best work? ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
```

2019-03-26 13:44 UTC, redreceipt commented on .github/PULL_REQUEST_TEMPLATE.md
>  - [ ] Closes [tag-issues-here]
```suggestion
- [ ] Closes [#ISSUE]
```

2019-03-27 16:59 UTC, redreceipt approved these changes
🤘

2019-03-27 19:49 UTC, merged