Adds For Staff Block
NewSpring/ApollosProject pull request #316
Opened 2019-10-15 21:11 UTC by redreceipt

## DESCRIPTION

### What does this PR do, or why is it needed?

Adds a block on the home feed that pulls from the staff news channel

### How do I test this PR?

Test it with and without yourself being in the staff group

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

2019-10-16 00:21 UTC, richarddubay requested changes

2019-10-16 00:21 UTC, richarddubay commented on packages/apollos-church-api/src/data/features/data-source.js
> +      .get();
I think we'll need to add a filter to make sure that the group member is active. I'm still seeing the staff block even though I set myself to inactive in the group. I think we can do something similar to what we do for groups in core. 
https://github.com/ApollosProject/apollos-prototype/blob/1fdc94a22ec5884b7549e6df079c86caec512aad/packages/apollos-data-connector-rock/src/groups/data-source.js#L20

2019-10-16 17:27 UTC, redreceipt commented
Don’t necessarily think that’s a problem, there’s no one in that group marked inactive. Plus this is a temp solution so I don’t wanna make it too involved.

—
Michael




> On Oct 15, 2019, at 8:21 PM, Richard Dubay <notifications@github.com> wrote:
> 
> @richarddubay requested changes on this pull request.
> 
> In packages/apollos-church-api/src/data/features/data-source.js <https://github.com/NewSpring/ApollosProject/pull/316#discussion_r335232318>:
> 
> > +    const staff = await this.request('GroupMembers')
> +      .andFilter(`GroupId eq 3`)
> +      .get();
> I think we'll need to add a filter to make sure that the group member is active. I'm still seeing the staff block even though I set myself to inactive in the group. I think we can do something similar to what we do for groups in core.
> https://github.com/ApollosProject/apollos-prototype/blob/1fdc94a22ec5884b7549e6df079c86caec512aad/packages/apollos-data-connector-rock/src/groups/data-source.js#L20 <https://github.com/ApollosProject/apollos-prototype/blob/1fdc94a22ec5884b7549e6df079c86caec512aad/packages/apollos-data-connector-rock/src/groups/data-source.js#L20>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/NewSpring/ApollosProject/pull/316?email_source=notifications&email_token=AAUJJFTUFVONJKJ3PHSXV7TQOZNBTA5CNFSM4JBDDUA2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCICDJZA#pullrequestreview-302265572>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAUJJFQ6T2G4N4YL3KIRYEDQOZNBTANCNFSM4JBDDUAQ>.
>

2019-10-17 12:10 UTC, redreceipt commented
ok @richarddubay good to test

2019-10-17 23:22 UTC, richarddubay approved these changes

2019-10-17 23:32 UTC, merged