Adds Guest Communicator
NewSpring/ApollosProject pull request #331
Opened 2019-10-22 15:44 UTC by richarddubay

## DESCRIPTION

### What does this PR do, or why is it needed?
This PR adds guest communicator abilities to the API and adds the addition of the guest communicator to the sermon notes.

### How do I test this PR?
Make sure all the sermons in the Elephant in the Room series work correctly and there are no errors.
Make sure that Miles McPherson's name shows up in the notes for The Third Option.

## TODO

- [x] I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))
- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android if applicable
- [x] Set a relevant reviewer

## REVIEW

- [ ] Review updates to test coverage and snapshots
- [ ] Review code through the lens of being concise, simple, and well-documented

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

---

> The purpose of PR Review is to _improve the quality of the software._

2019-10-22 16:47 UTC, redreceipt requested changes
discussed changes

2019-10-22 21:13 UTC, richarddubay commented
@redreceipt So I did extract out the `matrixItems` function to it's own function, but I didn't put it in it's own folder yet. Not sure if that's _really_ necessary. But ... I feel good about what's been done here!

2019-10-23 02:17 UTC, richarddubay commented
I looked at this a little bit more tonight. I'm not sure how to handle things like `this.request` in another `data-source` file. I might be able to figure it out, but it will probably take me longer than we have. If you know how to do that @redreceipt, I'm open to learning!

2019-10-23 16:44 UTC, redreceipt commented on packages/apollos-church-api/src/data/content-items/data-source.js
> +
don't need these

2019-10-23 16:45 UTC, redreceipt commented on packages/apollos-church-api/src/data/content-items/data-source.js
> +    const matrixItems = await MatrixItem.getMatrixItems(matrixItemGuid);
this function should prob `getFromGuid` and return a single item

2019-10-23 16:48 UTC, redreceipt commented on packages/apollos-church-api/src/data/content-items/data-source.js
> +    return communicators;
don't need this extra step, just return `Promise.all(items.map...`

2019-10-23 16:49 UTC, redreceipt commented on packages/apollos-church-api/src/data/content-items/data-source.js
> +      if (personAliasGuid !== '') {
```suggestion
      if (personAliasGuid === '') return null
```

2019-10-23 16:49 UTC, redreceipt commented on packages/apollos-church-api/src/data/content-items/data-source.js
> +      }
```suggestion
```

2019-10-23 16:49 UTC, redreceipt commented on packages/apollos-church-api/src/data/content-items/data-source.js
> +      return null;
```suggestion
```

2019-10-23 16:50 UTC, redreceipt commented on packages/apollos-church-api/src/data/content-items/data-source.js
> +    return guestCommunicators;
same as above, just return `Promise.all(items.map...`

2019-10-23 16:53 UTC, redreceipt commented on packages/apollos-church-api/src/data/matrix-items/data-source.js
> +    const matrixItems = await this.request('/AttributeMatrixItems')
return `this.request...`

2019-10-23 17:47 UTC, redreceipt approved these changes

2019-10-23 17:47 UTC, merged