[DEV-3745] Fixes How To Pray Screen Header Buttons
NewSpring/ApollosProject pull request #88
Opened 2019-05-20 15:56 UTC by cdanwards

## DESCRIPTION

We want a user to be able to navigate back to the `prayerlist` when we navigate to the `How To Pray` content single.

### What does this PR do, or why is it needed?

This PR adds the `isolated` prop to the navigation route, which helps the content single header determine which buttons to show. This is scalable to other instances when we want to navigate to a piece of content, but have it be stand alone.

### How do I test this PR?

Navigate to a prayer list then press `How to Pray` then navigate back to the `prayerlist`.

---

> I am affirming this is my _best_ work ([Ecclesiastes 9:10](https://www.bible.com/bible/97/ECC.9.10.MSG))

## TODO

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [DEV-XXX](#url)
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android if applicable
- [ ] Set two relevant reviewers

## REVIEW

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

---

> The purpose of PR Review is to _improve the quality of the software._

2019-05-20 18:11 UTC, redreceipt requested changes
Can't get to the content to test this functionality on Android, I'd say this is blocked by https://newspring.atlassian.net/browse/DEV-3780

2019-05-20 18:47 UTC, cdanwards commented
@redreceipt This behavior is also happening in master. Maybe that issue is out of scope of this PR. We can confirm that it works in ios.

2019-05-20 18:57 UTC, cdanwards commented
@richarddubay @IsaacHardy What do y'all think?

2019-05-20 19:38 UTC, redreceipt commented
But we can't confirm it works in Android, so if it doesn't we'll have to fix later.

2019-05-21 18:31 UTC, redreceipt approved these changes

2019-05-21 18:31 UTC, merged